language: python
python:
    - "2.7"
    - "3.4"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - "sudo apt-get install nsca"
    - "pip install -r requirements.txt -r requirements-tests.txt"
script: "nosetests tests"
